
# more themes: https://github.com/alacritty/alacritty-theme
import = [
    "~/.config/alacritty/one_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 160, lines = 45 }
decorations_theme_variant = "Dark"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 1

[cursor]
style = { shape = "Beam" }

[font]
size = 12.0

[font.normal]
# family = "Hack Nerd Font"
family = "JetBrains Mono Nerd Font"
style = "Regular"
