# more themes: https://github.com/alacritty/alacritty-theme

import = [
    "~/.config/alacritty/one_dark.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 160, lines = 45 }
decorations_theme_variant = "Dark"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 1

[cursor]
style = { shape = "Beam" }

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"
