
import = [
    "~/.config/alacritty/themes/themes/.catppuccin_frappe.toml"
]

live_config_reload = true

[window]
dimensions = { columns = 160, lines = 35 }
decorations_theme_variant = "Dark"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9

[cursor]
style = { shape = "Beam" }

[font]
size = 8.0
