
import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]

[window]
dimensions = { columns = 160, lines = 35 }
decorations_theme_variant = "Dark"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 1

[cursor]
style = { shape = "Beam" }

[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"
